# PostgreSQL Deployment для Service Management System
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: service-system
data:
  init.sql: |
    -- Инициализация базы данных для Service Management System
    DROP TABLE IF EXISTS Service_History CASCADE;
    DROP TABLE IF EXISTS Service_Types CASCADE;
    DROP TABLE IF EXISTS Devices CASCADE;

    CREATE TABLE Devices (
        device_id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        model VARCHAR(100),
        purchase_date DATE,
        status VARCHAR(20) DEFAULT 'active'
    );

    CREATE TABLE Service_Types (
        service_id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        recommended_interval_months INT,
        standard_cost DECIMAL(10,2)
    );

    CREATE TABLE Service_History (
        record_id SERIAL PRIMARY KEY,
        device_id INT REFERENCES Devices(device_id),
        service_id INT REFERENCES Service_Types(service_id),
        service_date DATE NOT NULL,
        cost DECIMAL(10,2),
        notes TEXT,
        next_due_date DATE
    );

    CREATE INDEX idx_due_dates ON Service_History(next_due_date) 
    WHERE next_due_date IS NOT NULL;

    INSERT INTO Devices (name, model, purchase_date, status) VALUES
        ('Printer HP LaserJet', 'HP LaserJet Pro', '2023-01-15', 'active'),
        ('Server Dell', 'PowerEdge R740', '2022-06-10', 'active'),
        ('Router Cisco', 'Cisco 2901', '2021-03-20', 'maintenance'),
        ('Workstation Dell', 'OptiPlex 7090', '2023-02-28', 'active'),
        ('UPS APC', 'Smart-UPS 1500', '2022-11-05', 'active');

    INSERT INTO Service_Types (name, recommended_interval_months, standard_cost) VALUES
        ('Замена тонера', 6, 50.00),
        ('Чистка и смазка', 12, 100.00),
        ('Замена HDD', 36, 150.00),
        ('Обновление прошивки', 12, 75.00),
        ('Проверка состояния', 3, 30.00);

    INSERT INTO Service_History (device_id, service_id, service_date, cost, notes, next_due_date) VALUES
        (1, 1, '2023-07-15', 50.00, 'Замена тонера TN-1030', '2024-01-15'),
        (1, 2, '2023-01-15', 100.00, 'Полная чистка', '2024-01-15'),
        (2, 4, '2023-06-10', 75.00, 'Обновление BIOS', '2024-06-10'),
        (3, 5, '2023-09-20', 30.00, 'Проверка конфигурации', '2023-12-20'),
        (4, 5, '2023-08-28', 30.00, 'Проверка системы', '2023-11-28'),
        (5, 2, '2023-05-05', 100.00, 'Замена батарей', '2024-05-05');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: service-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "car_service_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d/
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-init
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: service-system
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None

